print("What is your name?")
name=input()
print("What is your year of birth?")
DOB=int(input())
age=int(2023-DOB)
print("\n\n")
print(f"{name},\n\nlet's celebrate your {age} years of awesomeness!\n")
print(f"Wishing you a day filled with joy and laughter as you turn {age}.\n")
print("Thank you for filling out the questions!\n")
print("With love and best wishes\nSebastijan")